//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSWSWEBResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSWSWEBResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christopher Stewart Wine &amp; Spirits Inc. is a Canadian-based national importer dedicated to selecting and marketing high quality wines, spirits, beers, coolers and sakes from top producers around the World..
        /// </summary>
        public static string AboutContent_1 {
            get {
                return ResourceManager.GetString("AboutContent_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our goal is to bring unique and industry leading products to our customers through extensive research and an endless pursuit of quality. Our portfolio is an excellent reflection of our commitment to these on-going efforts..
        /// </summary>
        public static string AboutContent_2 {
            get {
                return ResourceManager.GetString("AboutContent_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In April of 2013, we expanded our operations internationally to China, with our Asian head office located in Hong Kong..
        /// </summary>
        public static string AboutContent_3 {
            get {
                return ResourceManager.GetString("AboutContent_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Me.
        /// </summary>
        public static string AboutMe {
            get {
                return ResourceManager.GetString("AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0},
        ///                                                           &lt;BR&gt;&lt;BR&gt;
        ///                                                            Please click on the link below to complete the registration process for your ChristopherStewart.com account.
        ///                                                            &lt;BR&gt;&lt;BR&gt;
        ///                                                            &lt;a href=&quot;http://www.christopherstewart.com/{1}/account/activeaccount/{2}&quot;&gt;http://www.christopherstewart.com/{1}/account/activeaccount/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ACCOUNT_ACTIVE_EMAIL_CONTENT {
            get {
                return ResourceManager.GetString("ACCOUNT_ACTIVE_EMAIL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChristopherStewart.com Account Registration.
        /// </summary>
        public static string ACTIVE_ACCOUNT_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("ACTIVE_ACCOUNT_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Account.
        /// </summary>
        public static string ActiveAccount {
            get {
                return ResourceManager.GetString("ActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your activation has been expired..
        /// </summary>
        public static string ActivtionExpired {
            get {
                return ResourceManager.GetString("ActivtionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency.
        /// </summary>
        public static string Agency {
            get {
                return ResourceManager.GetString("Agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Gallery.
        /// </summary>
        public static string ArtGallery {
            get {
                return ResourceManager.GetString("ArtGallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gallery_img_en.
        /// </summary>
        public static string ArtGalleryImgLink {
            get {
                return ResourceManager.GetString("ArtGalleryImgLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bringing the world&apos;s best to you!™.
        /// </summary>
        public static string BringTheBest {
            get {
                return ResourceManager.GetString("BringTheBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broker.
        /// </summary>
        public static string Broker {
            get {
                return ResourceManager.GetString("Broker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        public static string Canada {
            get {
                return ResourceManager.GetString("Canada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8 to 16 characters. Case sensitive..
        /// </summary>
        public static string CaseSensitive {
            get {
                return ResourceManager.GetString("CaseSensitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email address.
        /// </summary>
        public static string CfrmEmailAdd {
            get {
                return ResourceManager.GetString("CfrmEmailAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string CfrmPswd {
            get {
                return ResourceManager.GetString("CfrmPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm you are not a robot.
        /// </summary>
        public static string CfrmRobot {
            get {
                return ResourceManager.GetString("CfrmRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change email.
        /// </summary>
        public static string ChangeEmail {
            get {
                return ResourceManager.GetString("ChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Email.
        /// </summary>
        public static string ChangeEmailCapital {
            get {
                return ResourceManager.GetString("ChangeEmailCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePasswordCapital {
            get {
                return ResourceManager.GetString("ChangePasswordCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Profile.
        /// </summary>
        public static string ChangeProfile {
            get {
                return ResourceManager.GetString("ChangeProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Your Password.
        /// </summary>
        public static string ChangeYourPswd {
            get {
                return ResourceManager.GetString("ChangeYourPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a new email address and your current password below..
        /// </summary>
        public static string CHEInfo {
            get {
                return ResourceManager.GetString("CHEInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To change your password,enter your current password and a new password..
        /// </summary>
        public static string CHPInfo {
            get {
                return ResourceManager.GetString("CHPInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to upload image.
        /// </summary>
        public static string ClickUploadImg {
            get {
                return ResourceManager.GetString("ClickUploadImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to View.
        /// </summary>
        public static string ClickView {
            get {
                return ResourceManager.GetString("ClickView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CName {
            get {
                return ResourceManager.GetString("CName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Phone.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright ©.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new password.
        /// </summary>
        public static string CreateNewPswd {
            get {
                return ResourceManager.GetString("CreateNewPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buttons_pannel.
        /// </summary>
        public static string CSS_buttons_pannel {
            get {
                return ResourceManager.GetString("CSS_buttons_pannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to left_items.
        /// </summary>
        public static string CSS_left_items {
            get {
                return ResourceManager.GetString("CSS_left_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to right_items.
        /// </summary>
        public static string CSS_right_items {
            get {
                return ResourceManager.GetString("CSS_right_items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to td_share_input_caption_en.
        /// </summary>
        public static string CSS_TD_SHARE_INPUT_CPT {
            get {
                return ResourceManager.GetString("CSS_TD_SHARE_INPUT_CPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CSSBodySpace {
            get {
                return ResourceManager.GetString("CSSBodySpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hongkong_name_en.
        /// </summary>
        public static string CSSHKNameHolder {
            get {
                return ResourceManager.GetString("CSSHKNameHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ptfInfoHolder_en.
        /// </summary>
        public static string CSSPTFINFOHolder {
            get {
                return ResourceManager.GetString("CSSPTFINFOHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ptfTitleHolder_en.
        /// </summary>
        public static string CSSPTFTitleHolder {
            get {
                return ResourceManager.GetString("CSSPTFTitleHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to quote_space_text_en.
        /// </summary>
        public static string CSSQTSPACETEXT {
            get {
                return ResourceManager.GetString("CSSQTSPACETEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region_col_1_en.
        /// </summary>
        public static string CSSRegionCL1 {
            get {
                return ResourceManager.GetString("CSSRegionCL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region_col_2_en.
        /// </summary>
        public static string CSSRegionCL2 {
            get {
                return ResourceManager.GetString("CSSRegionCL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region_col_3_en.
        /// </summary>
        public static string CSSRegionCL3 {
            get {
                return ResourceManager.GetString("CSSRegionCL3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to region_col_4_en.
        /// </summary>
        public static string CSSRegionCL4 {
            get {
                return ResourceManager.GetString("CSSRegionCL4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title_ft_size_en.
        /// </summary>
        public static string CSSTitleFontSize {
            get {
                return ResourceManager.GetString("CSSTitleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christopher Stewart Wine &amp; Spirits.
        /// </summary>
        public static string CSWS {
            get {
                return ResourceManager.GetString("CSWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christopher Stewart Wine &amp; Spirits. All rights reserved.
        /// </summary>
        public static string CSWSARR {
            get {
                return ResourceManager.GetString("CSWSARR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christopher Stewart Wine &amp; Spirits is dedicated to selecting and importing high quality wines, spirits, beers, coolers and sakes from top producers around the world..
        /// </summary>
        public static string CSWSDescription {
            get {
                return ResourceManager.GetString("CSWSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo.png.
        /// </summary>
        public static string CSWSLogoImage {
            get {
                return ResourceManager.GetString("CSWSLogoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Christopher Stewart Quote.
        /// </summary>
        public static string CSWSQuote {
            get {
                return ResourceManager.GetString("CSWSQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distributor/Wholesaler.
        /// </summary>
        public static string DSAndWHS {
            get {
                return ResourceManager.GetString("DSAndWHS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile Photo.
        /// </summary>
        public static string EditProfilePhoto {
            get {
                return ResourceManager.GetString("EditProfilePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///                                                &lt;BR&gt;&lt;BR&gt;
        ///                                                Please click the link below to view and/or download the cover art &quot;{1}&quot;
        ///                                                &lt;BR&gt;&lt;BR&gt;
        ///                                                &lt;a href=&quot;http://www.christopherstewart.com/{2}/image/{3}&quot;&gt;http://www.christopherstewart.com/{2}/image/{3}&lt;/a&gt;
        ///                                                &lt;BR&gt;&lt;BR&gt;&lt;BR&gt;
        ///                                                E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string EMAIL_SHARE_CONTENT {
            get {
                return ResourceManager.GetString("EMAIL_SHARE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0},
        ///                                                      &lt;BR&gt;&lt;BR&gt;    
        ///                                                      {1} has sent you a link to the Christopher Stewart Cover Art &quot;{2}&quot; in High Resolution..
        /// </summary>
        public static string EMAIL_SHARE_SENDDER_MSG {
            get {
                return ResourceManager.GetString("EMAIL_SHARE_SENDDER_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emaill address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string FDBKComments {
            get {
                return ResourceManager.GetString("FDBKComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string FeedBack {
            get {
                return ResourceManager.GetString("FeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Christopher Stewart Wine &amp; Spirits, we are constantly striving for excellence in all aspects of our business. From the quality of our products, our Customer Service programs, and the educational content on our website, we value your opinion..
        /// </summary>
        public static string FeedBKContent_1 {
            get {
                return ResourceManager.GetString("FeedBKContent_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any suggestions or feedback on these topics - or any other aspect of Christopher Stewart - please complete the form below and send us your thoughts..
        /// </summary>
        public static string FeedBKContent_2 {
            get {
                return ResourceManager.GetString("FeedBKContent_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We value your comments and opinions and will return to you as soon as we can. Thank you!.
        /// </summary>
        public static string FeedBKContent_3 {
            get {
                return ResourceManager.GetString("FeedBKContent_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Submission.
        /// </summary>
        public static string FeedBKSubmission {
            get {
                return ResourceManager.GetString("FeedBKSubmission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FName {
            get {
                return ResourceManager.GetString("FName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string ForgetPswd {
            get {
                return ResourceManager.GetString("ForgetPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password.
        /// </summary>
        public static string ForgotPswd {
            get {
                return ResourceManager.GetString("ForgotPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        public static string HongKong {
            get {
                return ResourceManager.GetString("HongKong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level 12, Infinitus Plaza, 199 Des Voeux Road Central, Sheung Wan, Hong Kong..
        /// </summary>
        public static string HongKongAddress {
            get {
                return ResourceManager.GetString("HongKongAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospitality.
        /// </summary>
        public static string Hospitality {
            get {
                return ResourceManager.GetString("Hospitality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string HtmlLang {
            get {
                return ResourceManager.GetString("HtmlLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click here to save this high resolution cover art.
        /// </summary>
        public static string ImageSaveHR {
            get {
                return ResourceManager.GetString("ImageSaveHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        public static string Importer {
            get {
                return ResourceManager.GetString("Importer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industry.
        /// </summary>
        public static string Industry {
            get {
                return ResourceManager.GetString("Industry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string IndustryPortfolio {
            get {
                return ResourceManager.GetString("IndustryPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ~/js/language/message.en.js.
        /// </summary>
        public static string JS_MSG_FILE {
            get {
                return ResourceManager.GetString("JS_MSG_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en.
        /// </summary>
        public static string LanCode {
            get {
                return ResourceManager.GetString("LanCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s find your account.
        /// </summary>
        public static string LetsFindYRAcnt {
            get {
                return ResourceManager.GetString("LetsFindYRAcnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LName {
            get {
                return ResourceManager.GetString("LName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading, please wait.
        /// </summary>
        public static string LoadingImg {
            get {
                return ResourceManager.GetString("LoadingImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negociant.
        /// </summary>
        public static string Negociant {
            get {
                return ResourceManager.GetString("Negociant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the first to know! Get the latest news on upcoming events, new products and more, delivered straight to your inbox!.
        /// </summary>
        public static string NewLContent {
            get {
                return ResourceManager.GetString("NewLContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPswd {
            get {
                return ResourceManager.GetString("NewPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter.
        /// </summary>
        public static string Newsletter {
            get {
                return ResourceManager.GetString("Newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newsletter Sign Up.
        /// </summary>
        public static string NewsLetterTitle {
            get {
                return ResourceManager.GetString("NewsLetterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirmation.
        /// </summary>
        public static string PassworfCfrm {
            get {
                return ResourceManager.GetString("PassworfCfrm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Company name..
        /// </summary>
        public static string PleaseEnterCName {
            get {
                return ResourceManager.GetString("PleaseEnterCName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter First name..
        /// </summary>
        public static string PleaseEnterFName {
            get {
                return ResourceManager.GetString("PleaseEnterFName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter Last name..
        /// </summary>
        public static string PleaseEnterLName {
            get {
                return ResourceManager.GetString("PleaseEnterLName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your name..
        /// </summary>
        public static string PleaseEnterName {
            get {
                return ResourceManager.GetString("PleaseEnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address..
        /// </summary>
        public static string PleaseEnterValidEmail {
            get {
                return ResourceManager.GetString("PleaseEnterValidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the valid password, password must be at least 6 charactors..
        /// </summary>
        public static string PleaseEnterValidPswd {
            get {
                return ResourceManager.GetString("PleaseEnterValidPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the comment.
        /// </summary>
        public static string PleaseFillComment {
            get {
                return ResourceManager.GetString("PleaseFillComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the valid recipient&apos;s email address..
        /// </summary>
        public static string PLSENTERRCPName {
            get {
                return ResourceManager.GetString("PLSENTERRCPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portfolio.
        /// </summary>
        public static string Portfolio {
            get {
                return ResourceManager.GetString("Portfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PORTFOLIO.
        /// </summary>
        public static string PortfolioCapital {
            get {
                return ResourceManager.GetString("PortfolioCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016 December Edition Available.
        /// </summary>
        public static string PortfolioInfo {
            get {
                return ResourceManager.GetString("PortfolioInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alberta.
        /// </summary>
        public static string PRO_AB {
            get {
                return ResourceManager.GetString("PRO_AB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to British Columbia.
        /// </summary>
        public static string PRO_BC {
            get {
                return ResourceManager.GetString("PRO_BC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hong Kong.
        /// </summary>
        public static string PRO_HK {
            get {
                return ResourceManager.GetString("PRO_HK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manitoba.
        /// </summary>
        public static string PRO_MB {
            get {
                return ResourceManager.GetString("PRO_MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Brunswick.
        /// </summary>
        public static string PRO_NB {
            get {
                return ResourceManager.GetString("PRO_NB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Scotia.
        /// </summary>
        public static string PRO_NS {
            get {
                return ResourceManager.GetString("PRO_NS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontario.
        /// </summary>
        public static string PRO_ON {
            get {
                return ResourceManager.GetString("PRO_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quebec.
        /// </summary>
        public static string PRO_QB {
            get {
                return ResourceManager.GetString("PRO_QB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saskatchewan.
        /// </summary>
        public static string PRO_SK {
            get {
                return ResourceManager.GetString("PRO_SK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producer.
        /// </summary>
        public static string Producer {
            get {
                return ResourceManager.GetString("Producer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profit.
        /// </summary>
        public static string Profit {
            get {
                return ResourceManager.GetString("Profit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quote.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string QuoteMenu {
            get {
                return ResourceManager.GetString("QuoteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUOTE OF THE DAY.
        /// </summary>
        public static string QuoteOfDay {
            get {
                return ResourceManager.GetString("QuoteOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string Quotes {
            get {
                return ResourceManager.GetString("Quotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotes.
        /// </summary>
        public static string Quotes_MSG {
            get {
                return ResourceManager.GetString("Quotes_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.google.com/recaptcha/api.js?hl=en.
        /// </summary>
        public static string RechapchaLink {
            get {
                return ResourceManager.GetString("RechapchaLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear member,
        ///                                                            &lt;BR&gt;&lt;BR&gt;
        ///                                                            Per your request, please follow these steps to regain access to ChristopherStewart.com.
        ///                                                            &lt;BR&gt;&lt;BR&gt;
        ///                                                            1. Click the link below to choose a new password.
        ///                                                            &lt;BR&gt;&lt;BR&gt;
        ///                             [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RESET_PSWD_EMAIL_CONTENT {
            get {
                return ResourceManager.GetString("RESET_PSWD_EMAIL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChristopherStewart.com Account Request.
        /// </summary>
        public static string RESET_PSWD_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("RESET_PSWD_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Email.
        /// </summary>
        public static string ResetEmail {
            get {
                return ResourceManager.GetString("ResetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPswd {
            get {
                return ResourceManager.GetString("ResetPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Sales.
        /// </summary>
        public static string RetailSales {
            get {
                return ResourceManager.GetString("RetailSales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient&apos;s email.
        /// </summary>
        public static string RPEmail {
            get {
                return ResourceManager.GetString("RPEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recipient&apos;s name.
        /// </summary>
        public static string RPName {
            get {
                return ResourceManager.GetString("RPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Quote.
        /// </summary>
        public static string SearchQuote {
            get {
                return ResourceManager.GetString("SearchQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select city.
        /// </summary>
        public static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send me newsletters from Christopher Stewart Wine &amp; Spirits..
        /// </summary>
        public static string SendMeNews {
            get {
                return ResourceManager.GetString("SendMeNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Hi-Res Cover Art From Christopher Stewart Wine &amp; Spirits.
        /// </summary>
        public static string SHARE_EMAIL_SUBJECT {
            get {
                return ResourceManager.GetString("SHARE_EMAIL_SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this in Hi-Res.
        /// </summary>
        public static string ShareHR {
            get {
                return ResourceManager.GetString("ShareHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Hi-Res Cover Art.
        /// </summary>
        public static string ShareHRArt {
            get {
                return ResourceManager.GetString("ShareHRArt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To share the images please fill the information in below..
        /// </summary>
        public static string ShareInfo {
            get {
                return ResourceManager.GetString("ShareInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share Hi-Res Cover Art.
        /// </summary>
        public static string ShareTitle {
            get {
                return ResourceManager.GetString("ShareTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account.
        /// </summary>
        public static string SignInDHAct {
            get {
                return ResourceManager.GetString("SignInDHAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your industry email&lt;br&gt;
        ///and password.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing up now.
        /// </summary>
        public static string SignUpNow {
            get {
                return ResourceManager.GetString("SignUpNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember sign in information.
        /// </summary>
        public static string SignupRemember {
            get {
                return ResourceManager.GetString("SignupRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your industry segment.
        /// </summary>
        public static string SignUpSegment {
            get {
                return ResourceManager.GetString("SignUpSegment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Your Christopher Stewart Industry Account.
        /// </summary>
        public static string SignUpTitle {
            get {
                return ResourceManager.GetString("SignUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincerely,.
        /// </summary>
        public static string Sincerely {
            get {
                return ResourceManager.GetString("Sincerely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry your reset session has expired..
        /// </summary>
        public static string SorrySessionExpired {
            get {
                return ResourceManager.GetString("SorrySessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters. Avoid common words and names..
        /// </summary>
        public static string SpecialCharatorAvoidCommonWds {
            get {
                return ResourceManager.GetString("SpecialCharatorAvoidCommonWds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for registering for an Industry Account with ChristopherStewart.com..
        /// </summary>
        public static string ThankYouForRegisting {
            get {
                return ResourceManager.GetString("ThankYouForRegisting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Christopher Stewart Team.
        /// </summary>
        public static string TheCSWSTeam {
            get {
                return ResourceManager.GetString("TheCSWSTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toll free.
        /// </summary>
        public static string Tollfree {
            get {
                return ResourceManager.GetString("Tollfree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will now verify your industry status and active your account within 3 business days and email you back as soon as it is ready..
        /// </summary>
        public static string WeWillVerifyAccount {
            get {
                return ResourceManager.GetString("WeWillVerifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wine Maker.
        /// </summary>
        public static string WineMaker {
            get {
                return ResourceManager.GetString("WineMaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can unsubscribe at any time..
        /// </summary>
        public static string YouCanUnSub {
            get {
                return ResourceManager.GetString("YouCanUnSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current email address is.
        /// </summary>
        public static string YRCRTEmail {
            get {
                return ResourceManager.GetString("YRCRTEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your email.
        /// </summary>
        public static string YREmail {
            get {
                return ResourceManager.GetString("YREmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string YRName {
            get {
                return ResourceManager.GetString("YRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip/Postal Code.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
